apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: sample-php-hpa
  name: sample-php-hpa
spec:
  output:
    to:
      kind: ImageStreamTag
      name: sample-php-hpa:latest
  source:
    git:
      uri: https://github.com/yakiyoshi/sample-php-hpa.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.3
        namespace: openshift
    type: Source
  triggers:
  - type: ConfigChange
